version: "3.9"
services:
    keycloak:
        image:
            quay.io/keycloak/keycloak:16.1.0
        ports: 
            - "8081:8080"
            - "8444:8443"
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin123!
            KEYCLOAK_IMPORT: /tmp/apiman-realm-for-keycloak.json
            KEYCLOAK_FRONTEND_URL: http://${HOSTNAME}:2772/auth
            PROXY_ADDRESS_FORWARDING: 'true'
#            KEYCLOAK_LOGLEVEL: DEBUG
        volumes: 
            - ${PWD}/apiman-realm-for-keycloak.json:/tmp/apiman-realm-for-keycloak.json
    apiman:
        image:
            apiman/on-wildfly:wildfly-master
        ports:
            - "8085:8080"
        depends_on:
            - keycloak
        environment:
            APIMAN_AUTH_URL: http://${HOSTNAME}:2772/auth
