= Apiman Vert.x 3 Gateway
Marc Savy <marc@rhymewithgravy.com>
:toc: macro

This is an apiman gateway implemented using http://www.vertx.io[Vert.x 3].

toc::[]

== Running
You'll need to have a valid JSON config (see following sections), and build apiman with Java 8 (`mvn clean install`):

```shell
java -jar target/apiman-gateway-platforms-vertx3-1.2.10-SNAPSHOT-fat.jar -conf <path-to-your-config.json>
```

Replace `1.2.10-SNAPSHOT` with the version you built.

== Configuration

The counterpart to `apiman.properties` is a simple JSON-based configuration file, examples of which are provided in the https://github.com/apiman/apiman/blob/master/gateway/platforms/vertx3/vertx3/src/conf/[repository].

We'll use ElasticSearch components examples throughout this README.

=== Format

If you've used apiman before, then there's a simple and direct conversion between `apiman.properties` and `config.json`.

For example:

```json
{
  "client": {
    "type": "jest",
    "cluster-name": "elasticsearch",
    "host": "127.0.0.1",
    "port": "9200",
    "initialize": true,
    "apiman": ["great", "fantastic", "excellent"]
  }
}
```

Is equivalent to:

```properties
client.type=jest
client.cluster-name=elasticsearch
client.host=127.0.0.1
client.port=9200
client.initialize=true
client.apiman=great,fantastic,excellent
```
==== Comments

Unlike standard JSON, you can insert comments into the configuration by using C-style `// comment` syntax.

```json
{
  "foo": "bar" // This is a comment.
}
```

=== Registries and factories

```json
{
  "registry": {
    "class": "io.apiman.gateway.engine.es.ESCachingRegistry", // <1>
    "config": {
      "client": {
        "type": "jest",
        "cluster-name": "elasticsearch",
        "host": "127.0.0.1",
        "port": "9200",
        "initialize": true
      }
    }
  }
}
```
<1> Fully qualified path to registry class.

To configure a registry, component or factory, set the `class` to the corresponding fully qualified name of a valid implementation on the classpath.

You can pass arguments to the component using the `config` section.

=== Verticles

```json
{
  "verticles": {
    "http": { "port": 8082, "count": 1 },
    "https": { "port": 8443, "count": 1 },
    "api": { "port": 8081, "count": 1 }
  }
}
```

To scale your gateway, you can alter the number of verticles that will be spun up per-JVM when the project is deployed by changing `count`. Which port the verticle listens on can be changed with `port`.

If you don't want any instances of a particular verticle type, set its `count` to `0`.

NOTE: Verticle count only defines the number of verticles deployed in a given JVM instance (i.e. per `java -jar apiman<...>.jar -conf <...>`). How many deployments, and hence total number of verticles exist within your overall cluster is entirely up to you.

==== HTTP

Plaintext HTTP entry-point, with no transport security. Turn off by reducing count to zero.

==== HTTPS

Encrypted HTTPS entry-point, with TLS. Turn off by reducing count to zero.

==== API

Hosts the apiman gateway API, which is typically used by the apiman manager to drive the gateway. For instance, publishing and retiring APIs, Contracts.

=== Gateway API Authentication

NOTE: This only relates to apiman's Gateway API; it is *unrelated* to auth of traffic transiting the gateway.

```json
{
  "auth": {
    "required": "basic",
    "realm": "apiman-gateway",
    "basic": { // Password is SHA256 digest encoded as Base64.
      "admin" : "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg="
    }
  }
}
```

At present, there is only BASIC authentication support for the gateway API. You must provide a string key of your username and a Base64 encoded SHA256 hash of the corresponding password.

Here's a Ruby one-liner to achieve that for you:

```bash
ruby -e "require 'digest/sha2'; puts(Digest::SHA2.base64digest('admin'))"

$ jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=
```

=== Components

These are the various runtime components made available to apiman. They should be added to the `components` subsection of the config, but otherwise it's an identical pattern to the factories, etc.

```json
{
  "components": {
    "ISharedStateComponent": {
      "class": "io.apiman.gateway.engine.es.ESSharedStateComponent",
      "config": {
        "client": {
          "type": "jest",
          "cluster-name": "elasticsearch",
          "host": "127.0.0.1",
          "port": "9200",
          "initialize": true
        }
      }
    }
  }
}
```

In this example, we can see we're again using an ElasticSearch component, with the client configured in the `config` section.

TIP: Each component is standalone, so it may be that you need to repeat configuration in multiple components and registries.

=== Other

Most configuration options should be sufficiently annotated in the example configs to explain their purpose, a few others are worth briefly expanding upon.

==== Hostname

```json
{ "hostname": "localhost" }
```
The hostname to bind to.

==== Endpoint

```json
{ "endpoint": "mynode.local" }
```

Force the gateway to report the given gateway endpoint when it is queried by the manager. By default the gateway will inspect the request used to hit the Gateway API, and use whichever address was used to reach it as the endpoint.

==== Prefer Secure

```json
{ "preferSecure": true }
```

When reporting the gateway endpoint (as above), prefer to report the secure (HTTPS) URI rather than an insecure one (HTTP).

== TODO

- Enable auth to the Gateway API via Keycloak
