= Apiman Developer Guide
Marc Savy <marc@blackparrotlabs.io>, Eric Wittmann <eric.wittmann@redhat.com>
:doctype: book

== Introduction

Are you interested in contributing to the development of Apiman?
Maybe you want to embed the project in your own solution?
In either case, this is the guide for you.

[#_developer_resources]
== Developer Resources

This section describes a number of resources that are useful if you wish to contribute
code to Apiman.
It is likely also a good starting point for those wishing to provide functionality by implementing a plugin, although more information about plugins can be found in the 'Plugins' section.

include::Resources.adoc[]

== Architecture
The basic architecture of apiman is fairly straightforward.There are several WARs that
make up the default apiman installation.These include:

* API Manager REST back-end (JAX-RS WAR)
* API Manager UI (AngularJS/Hawtio WAR)
* API Gateway Config (JAX-RS WAR)
* API Gateway (Servlet WAR)

The API Manager REST back-end WAR is responsible for exposing a set of REST endpoints that
make up the API Manager REST interface.The API Manager UI uses this REST API
directly when the user manages the various entities in the data model.

The API Manager UI is a client-only AngularJS application.Aside from authentication
related activities, this WAR only contains HTML, JavaScript, and CSS.The UI uses
the browser to make direct, authenticated calls to the REST endpoints exposed by the
API Manager REST back-end WAR.

The API Gateway Config exposes the standard apiman Gateway REST API so that the API
Gateway can be remotely configured.This is the REST API that the API Manager uses
whenever a user publishes an API or registers a Client App.It is responsible
for configuring the API Gateway's embedded Policy Engine.

The API Gateway is the primary runtime component of apiman and is implemented as a
servlet that embeds the apiman Policy Engine.All requests to the API Gateway WAR are
assumed to be intended for managed APIs previously published to it.


