
=== Source Code

* The Apiman source code is located in GitHub here: https://github.com/apiman/apiman

* Source code for the Apiman policies can be found here: https://github.com/apiman/apiman-plugins

* Source code for the Apiman project web site is here: https://github.com/apiman/apiman.github.io

* The official Apiman docker files are currently here: https://github.com/apiman/apiman-docker

=== Issue Tracking

* Apiman uses link:https://www.github.com/apiman/apiman/issues[GitHub issues for tracking]. 

* You can ask questions https://www.github.com/apiman/apiman/discussions[on GitHub discussions]

=== Development Tools

We're rather IDE agnostic, so contributors should feel free to use whatever tools they feel most
comfortable with.  At the time of this writing, the core Apiman developers mostly use IntelliJ IDEA.

=== Building the Project

Building Apiman should be a simple matter of doing a standard Maven build:

[source,bash,subs=attributes+]
----
./mvnw clean install
----

This will do a full build of Apiman and execute all unit tests.  
However, the result will not include a ready-to-run version of Apiman.
For that, you may want to try the following:

[source,bash,subs=attributes+]
----
./mvnw clean install -Pinstall-all-wildfly
----

This command will do a full apiman build, but will also download WildFly and install Apiman into it.  
The result will be a fully configured install of Apiman running in WildFly.  
The location of this WildFly install will be here:

[source,bash,subs=attributes+]
----
apiman/tools/server-all/target/wildfly-{wildfly-version}/
----

At this point you can test Apiman by simply running WildFly from the above location using a command something like this:

[source,bash,subs=attributes+]
----
./bin/standalone.sh -b 0.0.0.0
----
