//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.04 at 01:49:18 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:io.apiman.test:2014:02:testPlan", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.apiman.test.common.plan;
