/// <reference path="../../includes.d.ts" />
declare module ApimanPageLifecycle {
    var pageTitles: {
        "page.title.admin-gateways": string;
        "page.title.admin-plugins": string;
        "page.title.admin-roles": string;
        "page.title.admin-policyDefs": string;
        "page.title.app-activity": string;
        "page.title.app-apis": string;
        "page.title.app-contracts": string;
        "page.title.app-metrics": string;
        "page.title.app-overview": string;
        "page.title.app-policies": string;
        "page.title.consumer-org": string;
        "page.title.consumer-orgs": string;
        "page.title.consumer-service": string;
        "page.title.consumer-service-def": string;
        "page.title.consumer-services": string;
        "page.title.dashboard": string;
        "page.title.about": string;
        "page.title.edit-gateway": string;
        "page.title.edit-policy": string;
        "page.title.edit-policyDef": string;
        "page.title.edit-role": string;
        "page.title.import-policyDefs": string;
        "page.title.import-services": string;
        "page.title.new-app": string;
        "page.title.new-app-version": string;
        "page.title.new-contract": string;
        "page.title.new-gateway": string;
        "page.title.new-member": string;
        "page.title.new-org": string;
        "page.title.new-plan": string;
        "page.title.new-plan-version": string;
        "page.title.new-plugin": string;
        "page.title.new-policy": string;
        "page.title.new-role": string;
        "page.title.new-service": string;
        "page.title.new-service-version": string;
        "page.title.org-activity": string;
        "page.title.org-apps": string;
        "page.title.org-manage-members": string;
        "page.title.org-members": string;
        "page.title.org-plans": string;
        "page.title.org-services": string;
        "page.title.plan-activity": string;
        "page.title.plan-overview": string;
        "page.title.plan-policies": string;
        "page.title.plugin-details": string;
        "page.title.policy-defs": string;
        "page.title.service-activity": string;
        "page.title.service-contracts": string;
        "page.title.service-endpoint": string;
        "page.title.service-metrics": string;
        "page.title.service-impl": string;
        "page.title.service-def": string;
        "page.title.service-overview": string;
        "page.title.service-plans": string;
        "page.title.service-policies": string;
        "page.title.user-activity": string;
        "page.title.user-apps": string;
        "page.title.user-orgs": string;
        "page.title.user-profile": string;
        "page.title.user-services": string;
        "page.title.error": string;
    };
    var _module: ng.IModule;
    var PageLifecycle: ng.IModule;
}
