//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.05 at 11:30:19 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:org.overlord.apiman.test:2014:02:testPlan", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.overlord.apiman.test.common.plan;
